# This is a basic workflow to help you get started with Actions

name: Automerge

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: release-*.*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    
    - name: Checkout latest master branch
      uses: actions/checkout@v2
      with:
          fetch-depth: 0
          ref: 'master'

   # In this step we are in the context of our develop branch because of the previous step.
    # the `./Scripts/ci_bump_develop.sh` will essentially compare the versions of develop and the current release branch (assume release-2.105 for this example).
    # Typically during codefreezes, both our develop and release branches will have a matching VERSION (2.105.0), so our nextVersion will be (2.106.0).
    # Note that subsequent pushes to a release branch will produce an empty string for nextVersion.
    # If our nextVersion is NOT empty, we set an output to notify subsequent steps that they need to run.
    - name: Compare release branch against develop
      id: compare
      run: |
        echo "::set-env name=RELEASE_BRANCH::2.109"
        echo ::set-output name=NEEDS_VERSION_BUMP::'true'

    # If we do NOT have a version bump and we are running this workflow, that means that there was subsequent changes to release branch (maybe HF).
      # We need to create a pull request from release branch into develop.
      # SUPER IMPORTANT: DO NOT DELETE THIS BRANCH AFTER MERGING.
    - name: Create pull request for release branch changes
      if: ${{ steps.compare.outputs.NEEDS_VERSION_BUMP != 'true' }}
      uses: peter-evans/create-pull-request@v3
      with:
          commit-message: Requesting merge from ${{ env.RELEASE_BRANCH }} into develop
          branch: automated-${{ env.RELEASE_BRANCH }}-merge
          delete-branch: false # IMPORTANT: DO NOT delete our release branch
          base: develop
          title: '[Automated] Release Changes Into Develop'
          body: |
            # Automated Release Pull Request
            - Merging changes from `$${{ env.RELEASE_BRANCH }}` into `develop`
            - Auto-generated by Automerge Github Action
          labels: |
            automated
            peer review
          reviewers: renamari,dpedley,jeffdp,ebresciano,seeegs,odunze
          draft: false
